name: Build Electron App

on:
  workflow_dispatch:
  push:
    branches: [ electron-build ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Install Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Install Electron deps
        run: |
          cd electron
          npm install

      - name: Build app
        run: |
          cd electron
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EmployeeManager-${{ matrix.os }}
          path: electron/dist/*